In [1]:
import numpy as np

In [2]:
x_data = np.loadtxt('/home/jovyan/2023 Research/CC200_X_corr.csv', delimiter = ',')

In [3]:
x_data.shape

(871, 20100)

In [5]:
transformed = np.empty(1005)
x_data_new = np.empty((871,1005))

In [12]:
def operation(pos):

    temp_data = np.empty(4)
    grouped = np.empty(5025)

    #start is starting index of operation
    x = 0

    for c in range(5025):
        #take average of 4 grouped data points
        temp = (x_data[pos][x] + x_data[pos][x+1] + x_data[pos][x+2] + x_data[pos][x+3]) / 4
        grouped[c] = 1/(1 + np.exp(-temp))
        #reLu operation
        #if grouped[c] <= 0:
            #grouped[c] = 0
        x+=4

    counter = 0

    #max pooling
    for y in range(1005):
        max = grouped[counter] 
        if max < grouped[counter+1]:
            max = grouped[counter+1]
        if max < grouped[counter+2]:
            max = grouped[counter+2]
        if max < grouped[counter+3]:
            max = grouped[counter+3]
        if max < grouped[counter+4]:
            max = grouped[counter+4]
        x_data_new[pos][y] = max
        counter += 5

In [13]:
for z in range(871):
    operation(z)

In [14]:
print(x_data_new)

[[0.65050356 0.61308793 0.60965277 ... 0.61199227 0.60341942 0.63699247]
 [0.61723516 0.5879927  0.59814396 ... 0.58721288 0.59472033 0.59141488]
 [0.62562287 0.59932712 0.63819688 ... 0.55043188 0.54728541 0.57191082]
 ...
 [0.60575882 0.59264916 0.60412633 ... 0.58585002 0.5950557  0.58661813]
 [0.58301844 0.56641714 0.57242556 ... 0.52351101 0.52668821 0.56792629]
 [0.61421862 0.61679054 0.61660688 ... 0.58142637 0.59537822 0.58768377]]


In [8]:
print(x_data)

[[ 7.07106781e-01  4.83429896e-01  7.07106781e-01 ...  4.02426613e-01
   2.87545309e-01  7.07106781e-01]
 [ 7.07106781e-01  2.05920464e-01  7.07106781e-01 ...  2.31941167e-01
  -3.09052902e-02  7.07106781e-01]
 [ 7.07106781e-01  2.26044758e-01  7.07106781e-01 ...  1.77765152e-01
  -8.09202474e-02  7.07106781e-01]
 ...
 [ 7.07106781e-01  6.62332106e-03  7.07106781e-01 ...  1.30890985e-01
   3.23909964e-02  7.07106781e-01]
 [ 7.07106781e-01 -9.12530743e-02  7.07106781e-01 ...  1.22021038e-01
  -3.46776199e-02  7.07106781e-01]
 [ 7.07106781e-01  2.00401269e-01  7.07106781e-01 ...  3.32824492e-01
  -2.04176731e-04  7.07106781e-01]]
